name: result-service
hostname: result

replicaCount: 1

image:
  repository: vucongtuanduong/grading-result
  tag: "v1.0.14"
  pullPolicy: Always

global:
  domain: vucongtuanduong.dpdns.org
  prefix: dev2

spring:
  profilesActive: stg

service:
  type: ClusterIP
  port: 8084

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
